# Generated by Django 4.2.4 on 2023-08-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('color', models.TextField()),
                ('texture', models.TextField()),
                ('has_grown', models.BooleanField()),
                ('position_on_body_x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position_on_body_y', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
