# Generated by Django 4.2.4 on 2023-09-13 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_user_id_mark_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='question',
        ),
        migrations.AddField(
            model_name='image',
            name='mark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mark_images', to='questions.mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='mark_images/'),
        ),
    ]
