# Generated by Django 4.2.4 on 2023-09-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_answer_remove_image_question_image_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='question',
            field=models.ManyToManyField(to='questions.question'),
        ),
    ]
